### PR TITLE
feature/lpfg 220

### PR DESCRIPTION
**Pull request by superafroman**
@elxsy  I think I've got a better way of extracting the resource IDs from the posted URLs. But take a look - keen to get feedback on if this is the right approach (specifically the posting of links back to do the update, rather than using the entity IDs.)

### CODE REVIEW

**Comment by elxsy** [comment]
Your approach is correct but finding and parsing Identifier's manually is not the right.

Maybe we should involve spring-data-rest?

https://stackoverflow.com/questions/43601604/converting-uri-to-entity-with-custom-controller-in-spring-data-rest/43617946

Which would do the translation for us and most of the expose operations.

I haven't played with it, can play tomorrow.

**Comment by superafroman** [comment]
Yeah, agree - that's what I'm looking at as a different approach :)

**Comment by ykurtbas** [comment]
Let's play around with that tomorrow then, might make some expose easier also. Less code the merrier

**Comment by superafroman** [comment]
@elxsy See updates - moved everything to spring-data-rest. Not sure I'm 100% happy with it but I'm sure we can refine the approach.

**Pull request merged**
